#!/bin/bash

# activating gtranslate
wp plugin activate gtranslate --allow-root

# forcing the gtranslate options so they're standard
wp option update GTranslate '{
  "pro_version": "",
  "enterprise_version": "",
  "wrapper_selector": ".gtranslate_wrapper",
  "custom_domains": "",
  "custom_domains_data": "",
  "url_translation": "",
  "add_hreflang_tags": "",
  "email_translation": "",
  "email_translation_debug": "",
  "show_in_menu": "",
  "floating_language_selector": "no",
  "native_language_names": "",
  "enable_cdn": "",
  "detect_browser_language": "",
  "add_new_line": 1,
  "select_language_label": "Select language",
  "custom_css": "",
  "default_language": "en",
  "widget_look": "dropdown",
  "flag_size": 24,
  "flag_style": "2d",
  "globe_size": 60,
  "globe_color": "#66aaff",
  "incl_langs": [
    "ar",
    "zh-CN",
    "nl",
    "en",
    "fr",
    "de",
    "it",
    "ja",
    "pt",
    "ru",
    "es",
    "yi"
  ],
  "fincl_langs": [
    "ar",
    "zh-CN",
    "nl",
    "en",
    "fr",
    "de",
    "it",
    "pt",
    "ru",
    "es"
  ],
  "alt_flags": [],
  "switcher_text_color": "#666",
  "switcher_arrow_color": "#666",
  "switcher_border_color": "#ccc",
  "switcher_background_color": "#fff",
  "switcher_background_shadow_color": "#efefef",
  "switcher_background_hover_color": "#fff",
  "dropdown_text_color": "#000",
  "dropdown_hover_color": "#fff",
  "dropdown_background_color": "#eee",
  "float_switcher_open_direction": "top",
  "switcher_open_direction": "top",
  "language_codes": "af,sq,am,ar,hy,az,eu,be,bn,bs,bg,ca,ceb,ny,zh-CN,zh-TW,co,hr,cs,da,nl,en,eo,et,tl,fi,fr,fy,gl,ka,de,el,gu,ht,ha,haw,iw,hi,hmn,hu,is,ig,id,ga,it,ja,jw,kn,kk,km,ko,ku,ky,lo,la,lv,lt,lb,mk,mg,ms,ml,mt,mi,mr,mn,my,ne,no,ps,fa,pl,pt,pa,ro,ru,sm,gd,sr,st,sn,sd,si,sk,sl,so,es,su,sw,sv,tg,ta,te,th,tr,uk,ur,uz,vi,cy,xh,yi,yo,zu",
  "language_codes2": "af,sq,am,ar,hy,az,eu,be,bn,bs,bg,ca,ceb,ny,zh-CN,zh-TW,co,hr,cs,da,nl,en,eo,et,tl,fi,fr,fy,gl,ka,de,el,gu,ht,ha,haw,iw,hi,hmn,hu,is,ig,id,ga,it,ja,jw,kn,kk,km,ko,ku,ky,lo,la,lv,lt,lb,mk,mg,ms,ml,mt,mi,mr,mn,my,ne,no,ps,fa,pl,pt,pa,ro,ru,sm,gd,sr,st,sn,sd,si,sk,sl,so,es,su,sw,sv,tg,ta,te,th,tr,uk,ur,uz,vi,cy,xh,yi,yo,zu"
}' --format=json --allow-root
